config/routes.rb
Filterizer::Application.routes.draw do
  resources :events do
    get :autocomplete_venue_name, on: :collection
  end
  resources :venues

  root 'home#index'

  get "/login" => "sessions#new", :as => :login
  post "/login" => "sessions#create", :as => :do_login
  delete "/logout" => "sessions#destroy", :as => :logout

end

app/models/event.rb
class Event < ActiveRecord::Base
  validates :venue, :title, :start_date, :end_date, presence: true
  belongs_to :venue

  MAX_TWEET_LENGTH = 140

  scope :opening_soon, -> { 
    includes(:venue)
      .includes(venue: :neighborhood)
      .where('opening_date >= ? AND opening_date <= ?', 
             Time.zone.now.to_date.to_s, 
             10.days.from_now.to_date.to_s).order("opening_date, opening_start_time") 
  }

  scope :opening_today, -> {
    date = Time.zone.now.to_date.to_s
    where('opening_date = ? or (opening_date IS NULL and start_date = ?)', 
          date, date).order("opening_start_time") 
  }

  scope :not_tweeted, -> { where(tweeted: false) }

  def url
    website.blank? ? venue.website : website
  end

  def venue_name
    venue.try(:name)
  end

  def tweeted!
    self.update_attributes(tweeted: true)
  end

  # open now, organized by hood
  def self.open_now
    list = []
    today = Time.zone.now.to_date.to_s

    Neighborhood.order("name").each do |neighborhood|
      events = Event.joins(:venue).where("venues.neighborhood_id = ? and start_date <= ? and end_date >= ?", 
                                         neighborhood.id, today, today)
                    .includes(:venue).order("end_date")
                    .includes(venue: :neighborhood)

      list << [ neighborhood.name, events ] unless events.empty?
    end
    list
  end

  # text for tweets
  def tweet_text
    text = "At #{venue.name}"
    text += " @#{venue.twitter}" if venue.twitter.present?
    text += ": #{title}"
    text = text.truncate(MAX_TWEET_LENGTH) if text.length > MAX_TWEET_LENGTH
    text
  end
  
end

app/models/neighborhood.rb
class Neighborhood < ActiveRecord::Base
  has_many :venues
  validates :name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password  
  
  validates :name, presence: true
  validates :password, presence: true, on: :create
end

app/models/venue.rb
class Venue < ActiveRecord::Base
  belongs_to :neighborhood
  validates :neighborhood, :name, :address, :website, presence: true
  has_many :events
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user  
    @current_user ||= User.find(session[:user_id]) if session[:user_id]  
  end  
  
  helper_method :current_user

  private

  # check whether admin is logged in
  def authenticate!
    unless current_user
      redirect_to login_path, notice: 'You must be logged in to visit that page'
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  layout 'admin'
  before_action :authenticate!
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  autocomplete :venue, :name

  # GET /events
  def index
    recent = (Time.zone.now.to_date - 10.days).to_s
    @events = Event.joins(:venue).where("end_date >= ?", recent).includes(:venue).order("end_date DESC")
  end

  # GET /events/1
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
    @event.opening_start_time = '18:00'
    @event.opening_end_time = '20:00'
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  def create
    @event = Event.new(event_params)

    if @event.save
      redirect_to @event, notice: 'Event was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /events/1
  def update
    if @event.update(event_params)
      redirect_to @event, notice: 'Event was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /events/1
  def destroy
    @event.destroy
    redirect_to events_url, notice: 'Event was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def event_params
    params.require(:event).permit(:title, :venue_id, :start_date, :end_date, :opening_date, :opening_start_time, :opening_end_time, :website)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    response.headers['Cache-Control'] = 'public, max-age=1800'
    @opening_soon = Event.opening_soon
    @open_now = Event.open_now
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController  
  layout 'admin'
  
  def new  
    redirect_to events_path if current_user
  end  

  def create  
    user = User.find_by_name(params[:name])  
    if user && user.authenticate(params[:password])  
      session[:user_id] = user.id  
      redirect_to events_path, notice: "Logged in!"  
    else  
      flash.now.alert = "Invalid email or password"  
      render "new"  
    end  
  end  

  def destroy  
    session[:user_id] = nil  
    redirect_to root_url, notice: "Logged out!"  
  end  
end  

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  layout 'admin'
  before_action :authenticate!
  before_action :set_venue, only: [:show, :edit, :update, :destroy]

  # GET /venues
  def index
    @venues = Venue.order("name").all
  end

  # GET /venues/1
  def show
  end

  # GET /venues/new
  def new
    @venue = Venue.new
  end

  # GET /venues/1/edit
  def edit
  end

  # POST /venues
  def create
    @venue = Venue.new(venue_params)

    if @venue.save
      redirect_to @venue, notice: 'Venue was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /venues/1
  def update
    if @venue.update(venue_params)
      redirect_to venues_url, notice: 'Venue was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /venues/1
  def destroy
    @venue.destroy
    redirect_to venues_url, notice: 'Venue was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_venue
    @venue = Venue.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def venue_params
    params.require(:venue).permit(:name, :neighborhood_id, :address, :website, :twitter)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def body_class
    [controller_name, action_name].join('-')
  end

  def opening_datetime(event)
    dt = "#{event.opening_date.strftime('%A, %B %e')}, #{event.opening_start_time.strftime('%l:%M')}-#{event.opening_end_time.strftime('%l:%M %p')}"
    dt.gsub!(/:00/, '')
    dt.gsub!(/^ /, '')
    dt.gsub(/  /, ' ')
    dt.gsub('- ', '-')
  end

  
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <% if false %>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <% end %>
  <div class="field">
    <%= f.label :venue %><br>
    <%= f.hidden_field :venue_id %>
    <%= f.autocomplete_field :venue_name, 
                             autocomplete_venue_name_events_path, 
                             id_element: '#event_venue_id' %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.text_field :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.text_field :end_date %>
  </div>
  <div class="field">
    <%= f.label :opening_date %><br>
    <%= f.text_field :opening_date %>
  </div>
  <div class="field">
    <%= f.label :opening_start_time %><br>
    <%= f.time_select :opening_start_time, minute_step: 30, ampm: true %>
  </div>
  <div class="field">
    <%= f.label :opening_end_time %><br>
    <%= f.time_select :opening_end_time, minute_step: 30, ampm: true %>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_field :website %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Listing events</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Venue</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Opening date</th>
      <th>Tweeted</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.title %></td>
        <td><%= event.venue.name %></td>
        <td><%= event.start_date %></td>
        <td><%= event.end_date %></td>
        <td><%= event.opening_date %></td>
        <td><%= event.tweeted %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<% if false %>
<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>
<% end %>

<p>
  <strong>Venue:</strong>
  <%= @event.venue.name %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @event.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @event.end_date %>
</p>

<p>
  <strong>Opening date:</strong>
  <%= @event.opening_date %>
</p>

<p>
  <strong>Opening start time:</strong>
  <%= @event.opening_start_time %>
</p>

<p>
  <strong>Opening end time:</strong>
  <%= @event.opening_end_time %>
</p>

<p>
  <strong>Website:</strong>
  <%= @event.website %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/home/index.html.erb
<% unless @opening_soon.blank? %>

  <h3>Openings</h3>

  <% @opening_soon.each do |opening| %>
  <div class="opening">
    <h4><span class="title"><%= opening.title %></span> at <%= link_to(opening.venue.name, opening.url) %></h4>
    <p class="opening-date"><%= opening_datetime(opening) %></p>
    <p class="address"><%= opening.venue.address %> [<%= opening.venue.neighborhood.name %>]</p>
  </div>
  <% end %>

<% end %>

<% unless @open_now.blank? %>

  <h3>Already Open</h3>

  <% @open_now.each do |now| %>

    <h4 class="neighborhood"><%= now.first %></h4>

    <% now.last.each do |event| %>
      <h4><span class="title"><%= event.title %></span> at <%= link_to(event.venue.name, event.url) %></h4>
      <p class="address"><%= event.venue.address %></p>
      <p class="closes">closes <%= event.end_date.strftime('%A, %B %e') %></p>
    <% end %>

  <% end %>

<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  	<title><%= content_for?(:title) ? yield(:title) : "Filterizer" %></title>

    <meta name="description" content="">
    <meta name="viewport" content="width=device-width">

    <%= stylesheet_link_tag "blueprint/screen.css" %>
    <!--[if lt IE 8]>
    <%= stylesheet_link_tag "blueprint/ie.css" %>
    <![endif]-->
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "admin.css" %>
  </head>

  <body class="<%= body_class %>">
    <div class="container">
    
      <section id="header">
        <h2><a href="/">FILTERIZER</a></h2>
        <% if current_user %>
          <p><%= link_to "venues", venues_path %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= link_to "events", events_path %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= link_to "logout", logout_path, :method => :delete %></p>
          <p><%= link_to "new venue", new_venue_path %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= link_to "new event", new_event_path %></p>
        <% end %>
      </section>

      <section id="main">
        <%= yield %>
      </section>

    </div>

    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= favicon_link_tag '/favicon.ico' %>
  	<title><%= content_for?(:title) ? yield(:title) : "Filterizer" %></title>

    <meta name="description" content="A one-page art show recommendation website from Barry Hoggard and James Wagner">
    <meta name="viewport" content="width=device-width">

    <%= javascript_include_tag "modernizr-2.6.2.min" %>
  	<%= stylesheet_link_tag    "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body class="<%= body_class %>">
    
    <section id="header">
      <h2><a href="/">FILTERIZER</a></h2>
    </section>

    <section id="main">
      <%= yield %>
    </section>

    <section id="footer">
      <p>A one-page art show recommendation website from <a href="https://twitter.com/bhoggard">@bhoggard</a> and <a href="https://twitter.com/wagnerblog">@wagnerblog</a>. Follow us on Twitter: <a href="https://twitter.com/filterizer">@filterizer</a>.</p>
    </section>

    <%= javascript_include_tag "application" %>

    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-43717201-1', 'filterizer.com');
      ga('send', 'pageview');

    </script>
  </body>
</html>

app/views/venues/_form.html.erb
<%= form_for(@venue) do |f| %>
  <% if @venue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@venue.errors.count, "error") %> prohibited this venue from being saved:</h2>

      <ul>
      <% @venue.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :neighborhood %><br>
    <%= f.collection_select(:neighborhood_id, Neighborhood.order('name ASC').all, :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :twitter %><br>
    <%= f.text_field :twitter %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/venues/edit.html.erb
<h1>Editing venue</h1>

<%= render 'form' %>

<%= link_to 'Show', @venue %> |
<%= link_to 'Back', venues_path %>

app/views/venues/index.html.erb
<h1>Listing venues</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Neighborhood</th>
      <th>Address</th>
      <th>Twitter</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @venues.each do |venue| %>
      <tr>
        <td><%= venue.name %></td>
        <td><%= venue.neighborhood.name %></td>
        <td><%= venue.address %></td>
        <td><%= venue.twitter %></td>
        <td><%= link_to 'Show', venue %></td>
        <td><%= link_to 'Edit', edit_venue_path(venue) %></td>
        <td><%= link_to 'Destroy', venue, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Venue', new_venue_path %>

app/views/venues/new.html.erb
<h1>New venue</h1>

<%= render 'form' %>

<%= link_to 'Back', venues_path %>

app/views/venues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @venue.name %>
</p>

<p>
  <strong>Neighborhood:</strong>
  <%= @venue.neighborhood.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @venue.address %>
</p>

<p>
  <strong>Website:</strong>
  <%= @venue.website %>
</p>

<%= link_to 'Edit', edit_venue_path(@venue) %> |
<%= link_to 'Back', venues_path %>